Repository careerfairsystems/arkad-app, pull requests merged in 2019-10, with the labels that each got.

#329 Backend start
  src/actions/api.js
  src/actions/logout.js
  src/actions/types.js
  src/components/StudentCard.js
  src/components/StudentList.js
  src/containers/ProfileScreenContainer.js
  src/containers/StudentCardContainer.js
  src/containers/StudentListContainer.js
  src/reducers/api.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#332 Connected backend with student list and card
  src/Router.js
  src/actions/api.js
  src/components/StudentList.js
  src/components/listItems/SelectableStudentListItem.js
  src/components/listItems/StudentListItem.js
  src/containers/ProfileScreenContainer.js
  src/containers/StudentListContainer.js
  src/reducers/api.js
  src/reducers/login.js
  src/screens/Companies/CompaniesScreen.js
  src/screens/Profile/CameraScreen.js
  src/screens/Profile/CompanyStudentCard.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#333 Connected qr scanning to backend
  src/Router.js
  src/actions/api.js
  src/actions/types.js
  src/components/StudentCard.js
  src/containers/CameraContainer.js
  src/reducers/api.js
  src/screens/Profile/CameraScreen.js
Labels: enhancement

#338 Need an account works
  src/actions/api.js
  src/components/StudentCard.js
  src/components/StudentList.js
  src/reducers/about.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#340 Removed hardcoded studentlist, FINALLYgit add .git add .
  src/actions/api.js
  src/components/StudentList.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#341 Connect remove student backend
  src/actions/api.js
  src/components/StudentCard.js
  src/components/StudentList.js
  src/containers/ProfileScreenContainer.js
  src/containers/StudentCardContainer.js
  src/containers/StudentListContainer.js
  src/reducers/api.js
  src/screens/Profile/CompanyStudentCard.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#344 Passwords removed
  src/actions/api.js
Labels: enhancement

#355 Default text added
  src/components/StudentList.js
Labels: enhancement

#354 Token correctly removed when loged out
  src/actions/api.js
  src/actions/logout.js
  src/components/StudentList.js
  src/reducers/api.js
  src/screens/Profile/CameraScreen.js
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#353 Can now drag to refresh in student list
  src/components/StudentList.js
  src/containers/StudentListContainer.js
Labels: enhancement

#370 Removed SafeAreaView
  App.js
Labels: enhancement

#377 Fix login screen
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#372 Fixed background color on text in username input
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#371 Remove button fixed and removed hard coded list in companystudenrtcard
  src/screens/Profile/CompanyStudentCard.js
Labels: bug

#381 No longer says null if comment is left empty
  src/screens/Profile/CompanyStudentCard.js
Labels: bug

#382 If studetn attribute null -> no error
  src/actions/api.js
  src/components/StudentCard.js
Labels: bug

#394 hopefully works
  package-lock.json
  package.json
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#391 Profile card design for students changed
  src/actions/api.js
  src/components/ButtonBar.js
  src/components/StudentCard.js
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#403 Header smaller icons
  src/Router.js
  src/components/LogoutButton.js
  src/components/ShowFavoritesButton.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#404 Bug gone
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#412 YEY
  src/reducers/api.js
  src/screens/Profile/CompanyStudentCard.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#414 maybe fixed camera flicker
  src/containers/CameraContainer.js
  src/reducers/api.js
  src/screens/Profile/CameraScreen.js
Labels: bug

#415 fixed
  src/screens/Profile/ProfileLoginScreen.js
Labels: bug

#420 Updated to 2019 FAQ
  src/reducers/about.js
Labels: enhancement

#421 Hope this works
  src/containers/CameraContainer.js
  src/screens/Profile/CameraScreen.js
Labels: enhancement

#423 Fixed
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#428 New line ios comment fixed
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#429 Rename camera to Scanner
  src/Router.js
Labels: bug, enhancement

#422 Remove add favorite from links, remove buttonBar from ocompany
  src/screens/Companies/CompanyDetailsScreen.js
Labels: bug

#430 Fixed
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#433 Fix not set comment input
  src/screens/Profile/CompanyStudentCard.js
Labels: bug

#434 Button bar func
  src/components/ButtonBar.js
  src/components/IconButton.js
  src/components/StudentCard.js
Labels: enhancement

#436 fixed
  src/screens/Profile/CameraScreen.js
  src/screens/Profile/CompanyStudentCard.js
Labels: bug

#439 YEY
  src/actions/api.js
  src/containers/ProfileScreenContainer.js
  src/screens/Profile/CameraScreen.js
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#440 Small fixes
  src/actions/api.js
Labels: bug

#444 Get actual data for cards
  src/components/StudentCard.js
  src/screens/Profile/CompanyStudentCard.js
Labels: enhancement

#445 Bump up version number and added offset to keyboardavoidingview
  ios/arkad_app_2018/Info.plist
  src/actions/api.js
  src/components/CVButton.js
  src/components/IconButton.js
  src/components/StudentCard.js
  src/containers/CompanyStudentCardContainer.js
  src/reducers/api.js
  src/screens/Profile/CompanyStudentCard.js
  src/screens/Profile/ProfileLoginScreen.js
Labels: enhancement

#450 Fixed
  src/components/StudentCard.js
  src/screens/Profile/CompanyStudentCard.js
Labels: bug
